on:
  workflow_dispatch:
  release:
    types: [created]

name: Build binary for release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Generate the artifacts
        uses: skx/github-action-build@master
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/x86_64-unknown-linux-musl/release/adapto-rs'
